version: '3'

services:
  unidamente: 
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - .:/node_modules
    command: nodemon app.js
